### ISSUE TITLE
Graphviz partially broken

### ISSUE THREAD

**Issue by hunteke** [hunteke/temoa#39]
To close #13, the commit 4386a0378ef033e850f3654a1938b3e814af99e9 removed `AddReportingVariables`.  Unfortunately, the Graphviz code relied on some of the redundant auxiliary variables that ARV created, so that commit broke Graphviz.

We should move Graphviz out of the core functionality of Temoa anyway, but perhaps not by breaking it.  Not sure the best approach, currently.

**Comment by hunteke** [comment]
For reference, here is the current result of trying to create Graphviz based graphics:

```
$ coopr_python temoa_model/ data_files/utopia-15.dat --graph_format svg > /dev/null
Notice: Using the CPLEX solver interface.
[    0.09] Reading data files.
[    0.46] Creating Temoa model instance.
[    0.59] Solving.
[    0.66] Calculating reporting variables and formatting results.
[        ] Creating Temoa model diagrams.Process Process-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "temoa_model/temoa_graphviz.py", line 1512, in do_work
  File "temoa_model/temoa_graphviz.py", line 1321, in CreateMainResultsDiagram
AttributeError: 'AbstractModel' object has no attribute 'V_EnergyConsumptionByPeriodInputAndTech'
^C

Temoa exit requested.  Exiting ...
```

It creates a few images, but fails before completing the gamut.  Luckily, the most important one that shows the basic unsolved energy system map still generates.
