### ISSUE TITLE
problems with trunk version  of coopr

### ISSUE THREAD

**Issue by shoibalc** [hunteke/temoa#6]
Some changes in the trunk definitely seems to have broken something.

$ python temoa_model.py temoa_island.dat 

[    0.22] Reading data files.
[        ] Creating Temoa model instance.ERROR: constructing declaration 'ModelLoanLife' from data=None failed
Traceback (most recent call last):
  File "temoa_model.py", line 297, in <module>
    temoa_solve( model )
  File "/home/shoibalc/pyworld/pyprojects/modelsinpyomo/temoa/temoa_model/temoa_lib.py", line 1074, in temoa_solve
    instance = model.create( mdata )
  File "/home/shoibalc/.virtualenvs/newcoopr/src/coopr.pyomo/coopr/pyomo/base/PyomoModel.py", line 166, in create
    data = coopr.core.CooprAPIFactory(self.config.create_functor)(self.config, model=self, *_kwargs)
  File "/home/shoibalc/.virtualenvs/newcoopr/src/pyutilib.workflow/pyutilib/workflow/task.py", line 113, in **call**
    self.execute()
  File "/home/shoibalc/.virtualenvs/newcoopr/src/coopr.core/coopr/core/_task.py", line 145, in execute
    retval = self._fn(data, *_self._kwds)
  File "/home/shoibalc/.virtualenvs/newcoopr/src/coopr.pyomo/coopr/pyomo/base/PyomoModel.py", line 838, in default_constructor
    instance.load(filename, namespaces=[None], profile_memory=profile_memory, report_timing=report_timing)
  File "/home/shoibalc/.virtualenvs/newcoopr/src/coopr.pyomo/coopr/pyomo/base/PyomoModel.py", line 375, in load
    self._load_model_data(arg, namespaces, profile_memory=profile_memory, report_timing=report_timing)
  File "/home/shoibalc/.virtualenvs/newcoopr/src/coopr.pyomo/coopr/pyomo/base/PyomoModel.py", line 540, in _load_model_data
    self._initialize_component(modeldata, namespaces, component_name, profile_memory)
  File "/home/shoibalc/.virtualenvs/newcoopr/src/coopr.pyomo/coopr/pyomo/base/PyomoModel.py", line 606, in _initialize_component
    declaration.construct(data)
  File "/home/shoibalc/.virtualenvs/newcoopr/src/coopr.pyomo/coopr/pyomo/base/param.py", line 369, in construct
    self, _init, self._parent(), idx )
  File "/home/shoibalc/.virtualenvs/newcoopr/src/coopr.pyomo/coopr/pyomo/base/misc.py", line 40, in apply_indexed_rule
    return rule(model, *index)
  File "/home/shoibalc/pyworld/pyprojects/modelsinpyomo/temoa/temoa_model/temoa_rules.py", line 100, in ParamModelLoanLife_rule
    loan_length = M.LifetimeLoan[t, v].value
AttributeError: 'int' object has no attribute 'value'

**Comment by hunteke** [comment]
You are indeed correct, the most recent trunk version of Coopr and Temoa don't play well.  I've just committed the necessary fixes, and have updated the downloadable temoa.py on http://temoaproject.org/

Thank you for pointing this out.

**Comment by hunteke** [comment]
I need to learn GitHub's markdown for in-commit referencing of issues.  Meanwhile, this is the commit that fixed this issue: 19963a6349a66c321538f5c92757f7f0b3550984
